### ISSUE TITLE
Groups and additional metadata

### ISSUE THREAD

**Issue by smith** [igrigorik/gmetric#2]
Metrics always show up in "no_group metrics." Add an option that lets you specify a group.

Here's a post that explains a patch done to the command line client that we could adapt for this: http://tobym.posterous.com/gmetric-track-and-group-arbitrary-metrics-wit

It also adds Description and Title, which might be nice too.

**Comment by igrigorik** [comment]
This is already possible, see example here: https://github.com/igrigorik/gmetric/blob/master/spec/gmetric_spec.rb#L79

**Comment by smith** [comment]
Oh, excellent. Sorry, I didn't see that in any of the examples and didn't try that key or read the tests :)

**Comment by igrigorik** [comment]
Definitely some room for improvement in the documentation. :-)
